// demos/employee-management/react/src/components/renderers/RatingDisplay.tsx
/**
 * RatingDisplay - Color-coded rating display
 * Matches Angular: app-rating-display
 */
interface RatingDisplayProps {
  value: number;
}

export function RatingDisplay({ value }: RatingDisplayProps) {
  const displayValue = (value ?? 0).toFixed(1);
  const level = value >= 4.5 ? 'high' : value >= 3.5 ? 'medium' : 'low';
  const levelClass = `rating-display--${level}`;

  return <span className={`rating-display ${levelClass}`}>{displayValue} ★</span>;
}

// demos/employee-management/angular/src/app/renderers/rating-display.component.ts
import { Component, computed, input } from '@angular/core';

@Component({
  selector: 'app-rating-display',
  template: `<span class="rating-display" [class]="levelClass()">{{ displayValue() }} ★</span>`,
  styles: [],
})
export class RatingDisplayComponent {
  value = input<number>(0);

  displayValue = computed(() => (this.value() ?? 0).toFixed(1));

  levelClass = computed(() => {
    const v = this.value() ?? 0;
    const level = v >= 4.5 ? 'high' : v >= 3.5 ? 'medium' : 'low';
    return `rating-display--${level}`;
  });
}
