// demos/vue/src/demos/employee-management/EmployeeManagement.vue
<script setup lang="ts">
/**
 * Employee Management Demo - Vue 3 Implementation
 *
 * This demo showcases @toolbox-web/grid-vue best practices:
 * - Feature imports for tree-shakeable plugin loading (side-effect imports)
 * - Feature props for declarative plugin configuration
 * - Event handling via @event-name syntax
 * - GridConfig for inline Vue renderers/editors
 * - TbwGridDetailPanel for declarative master-detail panels
 * - TbwGridToolPanel for custom sidebar panels
 * - TbwGridToolButtons for toolbar actions
 * - TbwGridResponsiveCard for responsive card layouts
 * - useGrid() composable for programmatic access
 * - TypeScript generics for row type safety
 *
 * The grid matches visual design and functionality across all framework demos.
 *
 * NOTE: Feature side-effect imports (`@toolbox-web/grid-vue/features/*`) live
 * next to the configuration in `./grid-config.ts`, since that's where the
 * matching `gridConfig.features` keys are declared.
 */

import {
  TbwGrid,
  TbwGridDetailPanel,
  TbwGridResponsiveCard,
  TbwGridToolButtons,
  TbwGridToolPanel,
  useGrid,
} from '@toolbox-web/grid-vue';
import { useGridExport } from '@toolbox-web/grid-vue/features/export';
import { computed, h, markRaw, ref } from 'vue';

// Import shared data, types, and styles
import { generateEmployees, type Employee } from '@demo/shared/employee-management';
import '@demo/shared/employee-management/demo-styles.css';

// Grid configuration (columns, groups, pinned rows, responsive, features)
import { createGridConfig } from './grid-config';

// Vue-specific renderers and editors
import BonusSliderEditor from './components/editors/BonusSliderEditor.vue';
import DateEditor from './components/editors/DateEditor.vue';
import StarRatingEditor from './components/editors/StarRatingEditor.vue';
import StatusSelectEditor from './components/editors/StatusSelectEditor.vue';
import DetailPanel from './components/renderers/DetailPanel.vue';
import RatingDisplay from './components/renderers/RatingDisplay.vue';
import ResponsiveEmployeeCard from './components/renderers/ResponsiveEmployeeCard.vue';
import StatusBadge from './components/renderers/StatusBadge.vue';
import TopPerformerStar from './components/renderers/TopPerformerStar.vue';
import AnalyticsPanel from './components/tool-panels/AnalyticsPanel.vue';
import QuickFiltersPanel from './components/tool-panels/QuickFiltersPanel.vue';

// ═══════════════════════════════════════════════════════════════════════════════
// STATE
// ═══════════════════════════════════════════════════════════════════════════════
const rowCount = ref(200);
const employees = ref<Employee[]>(generateEmployees(rowCount.value));

// Demo options - toggle features dynamically
const enableSelection = ref(true);
const enableFiltering = ref(true);
const enableSorting = ref(true);
const enableEditing = ref(true);
const enableMasterDetail = ref(true);

// useGrid() composable for programmatic access
const { gridElement } = useGrid<Employee>();

// useGridExport() for clean export API
const { exportToCsv, exportToExcel } = useGridExport<Employee>();

// ═══════════════════════════════════════════════════════════════════════════════
// HANDLERS
// ═══════════════════════════════════════════════════════════════════════════════
const handleRowCountChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  const newCount = parseInt(target.value, 10);
  rowCount.value = newCount;
  employees.value = generateEmployees(newCount);
};

// ═══════════════════════════════════════════════════════════════════════════════
// RENDERERS & EDITORS - Define outside computed to avoid recreating on each render
// ═══════════════════════════════════════════════════════════════════════════════

// Stable renderer functions that won't cause infinite loops
const renderers = {
  status: (value: string) => h(StatusBadge, { value }),
  rating: (value: number) => h(RatingDisplay, { value }),
  topPerformer: (value: boolean) => h(TopPerformerStar, { value }),
};

// Stable editor functions
const editors = {
  bonus: (value: number, salary: number, commit: (v: number) => void, cancel: () => void) =>
    h(BonusSliderEditor, { value, onCommit: commit, onCancel: cancel }),
  status: (value: string, commit: (v: string) => void, cancel: () => void) =>
    h(StatusSelectEditor, { value, onCommit: commit, onCancel: cancel }),
  date: (value: string, commit: (v: string) => void, cancel: () => void) =>
    h(DateEditor, { value, onCommit: commit, onCancel: cancel }),
  rating: (value: number, commit: (v: number) => void, cancel: () => void) =>
    h(StarRatingEditor, { value, onCommit: commit, onCancel: cancel }),
};

// ═══════════════════════════════════════════════════════════════════════════════
// GRID CONFIG
// ═══════════════════════════════════════════════════════════════════════════════

// Use markRaw to prevent Vue from deeply tracking the config object.
// This avoids infinite reactivity loops when the grid's internal state changes.
const gridConfig = computed(() =>
  markRaw(
    createGridConfig({
      enableSelection: enableSelection.value,
      enableFiltering: enableFiltering.value,
      enableSorting: enableSorting.value,
      enableEditing: enableEditing.value,
      enableMasterDetail: enableMasterDetail.value,
      renderers,
      editors,
    }),
  ),
);
</script>

<template>
  <div id="app">
    <div class="demo-container">
      <!-- Demo Controls Header -->
      <header class="demo-header">
        <div class="demo-controls">
          <label>
            <span class="row-count-display">
              Rows: <strong>{{ rowCount }}</strong>
            </span>
            <input type="range" min="50" max="1000" step="50" :value="rowCount" @input="handleRowCountChange" />
          </label>
          <label> <input type="checkbox" v-model="enableSelection" /> Selection </label>
          <label> <input type="checkbox" v-model="enableFiltering" /> Filtering </label>
          <label> <input type="checkbox" v-model="enableSorting" /> Sorting </label>
          <label> <input type="checkbox" v-model="enableEditing" /> Editing </label>
          <label> <input type="checkbox" v-model="enableMasterDetail" /> Master-Detail </label>
        </div>
      </header>

      <!-- Grid -->
      <div class="grid-wrapper">
        <TbwGrid :rows="employees" :gridConfig="gridConfig" class="demo-grid">
          <!-- Toolbar buttons -->
          <TbwGridToolButtons>
            <button
              class="tbw-toolbar-btn"
              title="Export CSV"
              aria-label="Export CSV"
              @click="exportToCsv('employees.csv')"
            >
              📄
            </button>
            <button
              class="tbw-toolbar-btn"
              title="Export Excel"
              aria-label="Export Excel"
              @click="exportToExcel('employees.xlsx')"
            >
              📊
            </button>
          </TbwGridToolButtons>

          <!-- Custom tool panels -->
          <TbwGridToolPanel id="quick-filters" title="Quick Filters" icon="🔍">
            <template #default="{ grid }">
              <QuickFiltersPanel @filter-change="(filters) => console.log('Filters:', filters)" />
            </template>
          </TbwGridToolPanel>

          <TbwGridToolPanel id="analytics" title="Analytics" icon="📈">
            <template #default="{ grid }">
              <AnalyticsPanel :rows="employees" />
            </template>
          </TbwGridToolPanel>

          <!-- Master-detail panel -->
          <TbwGridDetailPanel v-if="enableMasterDetail">
            <template #default="{ row }">
              <DetailPanel :row="row" />
            </template>
          </TbwGridDetailPanel>

          <!-- Responsive card for mobile/narrow layouts -->
          <TbwGridResponsiveCard>
            <template #default="{ row }">
              <ResponsiveEmployeeCard :row="row" />
            </template>
          </TbwGridResponsiveCard>
        </TbwGrid>
      </div>
    </div>
  </div>
</template>

// demos/react/src/demos/employee-management/EmployeeManagement.tsx
/**
 * Employee Management Demo - React Implementation
 *
 * This demo showcases @toolbox-web/grid-react best practices:
 * - Feature imports for tree-shakeable plugin loading (side-effect imports)
 * - Feature props for declarative plugin configuration
 * - Event props for automatic cleanup (no useEffect for events)
 * - GridConfig for inline React renderers/editors
 * - GridDetailPanel for declarative master-detail panels
 * - GridToolPanel for custom sidebar panels
 * - GridToolButtons for toolbar actions
 * - Enhanced useGrid with convenience methods
 *
 * The grid matches visual design and functionality across all framework demos.
 *
 * NOTE: Feature side-effect imports (`@toolbox-web/grid-react/features/*`) live
 * next to the configuration in `./grid-config.ts`, since that's where the
 * matching `gridConfig.features` keys are declared.
 */

import {
  DataGrid,
  GridDetailPanel,
  GridResponsiveCard,
  GridToolButtons,
  GridToolPanel,
  useGrid,
  type DetailPanelContext,
  type ResponsiveCardContext,
  type ToolPanelContext,
} from '@toolbox-web/grid-react';
import { useGridExport } from '@toolbox-web/grid-react/features/export';
import { useCallback, useMemo, useState } from 'react';

// Import shared data, types, and styles
import { generateEmployees, type Employee } from '@demo/shared/employee-management';
import { shadowDomStyles } from '@demo/shared/employee-management/styles';

// Grid configuration (columns, groups, pinned rows, responsive, features)
import { createGridConfig } from './grid-config';

// React-specific renderers and editors
import { BonusSliderEditor } from './components/editors/BonusSliderEditor';
import { DateEditor } from './components/editors/DateEditor';
import { StarRatingEditor } from './components/editors/StarRatingEditor';
import { StatusSelectEditor } from './components/editors/StatusSelectEditor';
import { DetailPanel } from './components/renderers/DetailPanel';
import { RatingDisplay } from './components/renderers/RatingDisplay';
import { ResponsiveEmployeeCard } from './components/renderers/ResponsiveEmployeeCard';
import { StatusBadge } from './components/renderers/StatusBadge';
import { TopPerformerStar } from './components/renderers/TopPerformerStar';
import { AnalyticsPanel, QuickFiltersPanel } from './components/tool-panels';

export function EmployeeManagement() {
  // ═══════════════════════════════════════════════════════════════════════════
  // STATE
  // ═══════════════════════════════════════════════════════════════════════════
  const [rowCount, setRowCount] = useState(200);
  const [employees, setEmployees] = useState<Employee[]>(() => generateEmployees(rowCount));

  // Demo options - toggle features dynamically
  const [enableSelection, setEnableSelection] = useState(true);
  const [enableFiltering, setEnableFiltering] = useState(true);
  const [enableSorting, setEnableSorting] = useState(true);
  const [enableEditing, setEnableEditing] = useState(true);
  const [enableMasterDetail, setEnableMasterDetail] = useState(true);

  // Enhanced useGrid for ref access
  const { ref } = useGrid<Employee>();

  // Feature-scoped hook for export control
  const { exportToCsv, exportToExcel } = useGridExport<Employee>();

  // ═══════════════════════════════════════════════════════════════════════════
  // HANDLERS
  // ═══════════════════════════════════════════════════════════════════════════
  const handleRowCountChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const newCount = parseInt(e.target.value, 10);
    setRowCount(newCount);
    setEmployees(generateEmployees(newCount));
  }, []);

  // ═══════════════════════════════════════════════════════════════════════════
  // GRID CONFIG
  // ═══════════════════════════════════════════════════════════════════════════
  const gridConfig = useMemo(
    () =>
      createGridConfig({
        enableSelection,
        enableFiltering,
        enableSorting,
        enableEditing,
        enableMasterDetail,
        // Renderers - map value to JSX
        renderers: {
          status: (value) => <StatusBadge value={value} />,
          rating: (value) => <RatingDisplay value={value} />,
          topPerformer: (value) => <TopPerformerStar value={value} />,
        },
        // Editors - map value + callbacks to JSX
        editors: {
          bonus: (value, salary, commit, cancel) => (
            <BonusSliderEditor value={value} salary={salary} onCommit={commit} onCancel={cancel} />
          ),
          status: (value, commit, cancel) => <StatusSelectEditor value={value} onCommit={commit} onCancel={cancel} />,
          date: (value, commit, cancel) => <DateEditor value={value} onCommit={commit} onCancel={cancel} />,
          rating: (value, commit, cancel) => <StarRatingEditor value={value} onCommit={commit} onCancel={cancel} />,
        },
      }),
    [enableSelection, enableFiltering, enableSorting, enableEditing, enableMasterDetail],
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════════════════════════════════════════
  return (
    <div id="app">
      <div className="demo-container">
        {/* Demo Controls Header */}
        <header className="demo-header">
          <div className="demo-controls">
            <label>
              <span className="row-count-display">
                Rows: <strong>{rowCount}</strong>
              </span>
              <input type="range" min="50" max="1000" step="50" value={rowCount} onChange={handleRowCountChange} />
            </label>
            <label>
              <input type="checkbox" checked={enableSelection} onChange={(e) => setEnableSelection(e.target.checked)} />{' '}
              Selection
            </label>
            <label>
              <input type="checkbox" checked={enableFiltering} onChange={(e) => setEnableFiltering(e.target.checked)} />{' '}
              Filtering
            </label>
            <label>
              <input type="checkbox" checked={enableSorting} onChange={(e) => setEnableSorting(e.target.checked)} />{' '}
              Sorting
            </label>
            <label>
              <input type="checkbox" checked={enableEditing} onChange={(e) => setEnableEditing(e.target.checked)} />{' '}
              Editing
            </label>
            <label>
              <input
                type="checkbox"
                checked={enableMasterDetail}
                onChange={(e) => setEnableMasterDetail(e.target.checked)}
              />{' '}
              Master-Detail
            </label>
          </div>
        </header>

        {/* Grid */}
        <div className="grid-wrapper">
          <DataGrid
            ref={ref}
            rows={employees}
            gridConfig={gridConfig}
            customStyles={shadowDomStyles}
            className="demo-grid"
            // Features are configured declaratively inside `gridConfig.features`
            // (see `grid-config.ts`). Keeps the template tidy and lets the same
            // config drive the docs demo.
            // ═══════════════════════════════════════════════════════════════
            // EVENT PROPS - Automatic cleanup, no useEffect needed
            // ═══════════════════════════════════════════════════════════════
            onRowsChange={setEmployees}
          >
            {/* Toolbar buttons */}
            <GridToolButtons>
              <button
                className="tbw-toolbar-btn"
                title="Export CSV"
                aria-label="Export CSV"
                onClick={() => exportToCsv('employees.csv')}
              >
                📄
              </button>
              <button
                className="tbw-toolbar-btn"
                title="Export Excel"
                aria-label="Export Excel"
                onClick={() => exportToExcel('employees.xlsx')}
              >
                📊
              </button>
            </GridToolButtons>

            {/* Custom tool panels */}
            <GridToolPanel id="quick-filters" title="Quick Filters" icon="🔍" order={10}>
              {({ grid }: ToolPanelContext) => <QuickFiltersPanel grid={grid} />}
            </GridToolPanel>

            <GridToolPanel id="analytics" title="Analytics" icon="📈" order={20}>
              {({ grid }: ToolPanelContext) => <AnalyticsPanel grid={grid} />}
            </GridToolPanel>

            {/* Master-detail panel */}
            {enableMasterDetail && (
              <GridDetailPanel<Employee>>
                {({ row }: DetailPanelContext<Employee>) => <DetailPanel employee={row} />}
              </GridDetailPanel>
            )}

            {/* Responsive card for mobile/narrow layouts */}
            <GridResponsiveCard<Employee>>
              {({ row }: ResponsiveCardContext<Employee>) => <ResponsiveEmployeeCard employee={row} />}
            </GridResponsiveCard>
          </DataGrid>
        </div>
      </div>
    </div>
  );
}
