// demos/react/src/demos/calendar/Calendar.tsx
import '@toolbox-web/grid-react/features/pinned-rows';
import './Calendar.css';

import type { CalendarDay, CalendarEvent, CalendarWeek, WeekdayField } from '@demo/shared/calendar';
import {
  buildWeeks,
  generateEvents,
  isoKey,
  WEEKDAY_FIELDS,
  WEEKDAY_HEADERS,
  WEEKDAY_HEADERS_FULL,
  WEEKDAY_HEADERS_MINI,
} from '@demo/shared/calendar';
import { DataGrid, useGrid, type GridConfig } from '@toolbox-web/grid-react';
import { useCallback, useEffect, useMemo, useReducer, useRef, useState } from 'react';

import { DayCell } from './components/DayCell';
import { EventDialog } from './components/EventDialog';
import { HeaderNav } from './components/HeaderNav';
import { Legend } from './components/Legend';
import { ToolbarNav } from './components/ToolbarNav';
import { useDoubleClick } from './hooks/useDoubleClick';
import { useDynamicRowHeight } from './hooks/useDynamicRowHeight';
import { useGridCallbackRoot } from './hooks/useGridCallbackRoot';
import { findDayPosition, useKeyboardNav, type PendingFocus } from './hooks/useKeyboardNav';

const DEFAULT_ROW_HEIGHT_PX = 110;

type UserEvents = Record<string, CalendarEvent[]>;

interface CalendarState {
  year: number;
  month: number;
  userEvents: UserEvents;
}

type CalendarAction =
  | { type: 'set-view'; year: number; month: number }
  | { type: 'shift-month'; delta: number }
  | { type: 'today' }
  | { type: 'set-year'; year: number }
  | { type: 'add-event'; day: CalendarDay; event: CalendarEvent };

function initialState(): CalendarState {
  const today = new Date();
  return { year: today.getFullYear(), month: today.getMonth(), userEvents: {} };
}

function calendarReducer(state: CalendarState, action: CalendarAction): CalendarState {
  switch (action.type) {
    case 'set-view':
      return { ...state, year: action.year, month: action.month };
    case 'shift-month': {
      const next = new Date(state.year, state.month + action.delta, 1);
      return { ...state, year: next.getFullYear(), month: next.getMonth() };
    }
    case 'today': {
      const today = new Date();
      return { ...state, year: today.getFullYear(), month: today.getMonth() };
    }
    case 'set-year':
      return { ...state, year: action.year };
    case 'add-event': {
      const key = isoKey(action.day.date);
      const existing = state.userEvents[key] ?? [];
      const nextEvents = [...existing, action.event].sort((a, b) => a.startTime.localeCompare(b.startTime));
      return { ...state, userEvents: { ...state.userEvents, [key]: nextEvents } };
    }
  }
}

function makeRows(state: CalendarState): CalendarWeek[] {
  const generated = generateEvents(state.year, state.month);
  const byDate = new Map(generated.byDate);

  for (const [key, events] of Object.entries(state.userEvents) as [string, CalendarEvent[]][]) {
    const existing = (byDate.get(key) ?? []) as CalendarEvent[];
    const merged = [...existing, ...events].sort((a: CalendarEvent, b: CalendarEvent) =>
      a.startTime.localeCompare(b.startTime),
    );
    byDate.set(key, merged);
  }

  return buildWeeks(state.year, state.month, byDate);
}

function WeekdayHeader({ field }: { field: WeekdayField }) {
  return (
    <span className="cal-wday">
      <span className="cal-wday__full">{WEEKDAY_HEADERS_FULL[field]}</span>
      <span className="cal-wday__short">{WEEKDAY_HEADERS[field]}</span>
      <span className="cal-wday__mini">{WEEKDAY_HEADERS_MINI[field]}</span>
    </span>
  );
}

function resolveDayFromCell(rows: readonly CalendarWeek[], cell: HTMLElement): CalendarDay | null {
  const colIndex = Number(cell.getAttribute('data-col'));
  if (!Number.isFinite(colIndex) || colIndex <= 0) return null;

  const row = cell.closest<HTMLElement>('.data-grid-row');
  const ariaRowIndex = Number(row?.getAttribute('aria-rowindex'));
  if (!Number.isFinite(ariaRowIndex)) return null;

  const week = rows[ariaRowIndex - 2];
  const field = WEEKDAY_FIELDS[colIndex - 1];
  return field && week ? week[field] : null;
}

export function Calendar() {
  const [state, dispatch] = useReducer(calendarReducer, undefined, initialState);
  const [dialogDay, setDialogDay] = useState<CalendarDay | null>(null);
  const grid = useGrid<CalendarWeek>();
  const callbackRoot = useGridCallbackRoot();
  const pendingFocusRef = useRef<PendingFocus | null>(null);
  // Cache the legend container so the pinned-rows plugin can short-circuit
  // DOM mutation across grid renders (fresh element each call = unmount loop).
  const legendElementRef = useRef<HTMLElement | null>(null);

  const rows = useMemo(() => makeRows(state), [state]);

  const setView = useCallback((year: number, month: number, focus?: PendingFocus) => {
    pendingFocusRef.current = focus ?? null;
    dispatch({ type: 'set-view', year, month });
  }, []);

  const gridConfig = useMemo<GridConfig<CalendarWeek>>(
    () => ({
      fitMode: 'stretch',
      shell: { header: { toolPanelToggle: false } },
      rowHeight: DEFAULT_ROW_HEIGHT_PX,
      features: {
        pinnedRows: {
          slots: [
            {
              id: 'calendar-legend',
              position: 'bottom',
              render: () => {
                if (!legendElementRef.current) {
                  legendElementRef.current = callbackRoot.renderElement(<Legend />);
                }
                return legendElementRef.current;
              },
            },
          ],
        },
      },
      columns: [
        {
          field: 'weekNumber',
          header: 'W',
          width: 44,
          sortable: false,
          resizable: false,
          cellClass: () => 'cal-week-cell',
        },
        ...WEEKDAY_FIELDS.map((field: WeekdayField) => ({
          field,
          header: WEEKDAY_HEADERS_FULL[field],
          headerLabelRenderer: () => <WeekdayHeader field={field} />,
          minWidth: 60,
          sortable: false,
          resizable: false,
          renderer: (ctx: { value: CalendarDay }) => <DayCell day={ctx.value} />,
        })),
      ],
    }),
    [callbackRoot],
  );

  useEffect(() => {
    if (!grid.isReady) return;
    const gridElement = grid.ref.current?.element;
    if (!gridElement) return;

    gridElement.registerHeaderContent?.({
      id: 'calendar-nav',
      order: 0,
      render: (container: HTMLElement) =>
        callbackRoot.renderInto(
          container,
          <HeaderNav
            year={state.year}
            month={state.month}
            onYearChange={(year) => dispatch({ type: 'set-year', year })}
          />,
        ),
    });
    gridElement.registerToolbarContent?.({
      id: 'calendar-nav-buttons',
      order: 0,
      render: (container: HTMLElement) =>
        callbackRoot.renderInto(
          container,
          <ToolbarNav
            onPrevious={() => dispatch({ type: 'shift-month', delta: -1 })}
            onToday={() => {
              const today = new Date();
              pendingFocusRef.current = { day: today.getDate() };
              dispatch({ type: 'today' });
            }}
            onNext={() => dispatch({ type: 'shift-month', delta: 1 })}
          />,
        ),
    });
    gridElement.refreshShellHeader?.();

    return () => {
      gridElement.unregisterHeaderContent?.('calendar-nav');
      gridElement.unregisterToolbarContent?.('calendar-nav-buttons');
    };
  }, [callbackRoot, grid.isReady, grid.ref, state.month, state.year]);

  useEffect(() => {
    const target = pendingFocusRef.current;
    if (!target || !grid.isReady) return;
    const gridElement = grid.ref.current?.element;
    if (!gridElement) return;

    const position =
      'day' in target
        ? findDayPosition(rows, state.year, state.month, target.day)
        : {
            rowIndex: Math.min(target.position.rowIndex, Math.max(rows.length - 1, 0)),
            colIndex: target.position.colIndex,
          };
    pendingFocusRef.current = null;
    if (position) queueMicrotask(() => gridElement.focusCell?.(position.rowIndex, position.colIndex));
  }, [grid.isReady, grid.ref, rows, state.month, state.year]);

  const openDialog = useCallback((day: CalendarDay) => setDialogDay(day), []);

  useKeyboardNav({ gridRef: grid.ref, enabled: grid.isReady, rows, view: state, setView, openDialog });
  useDynamicRowHeight(grid.ref, grid.isReady, rows.length, gridConfig);
  useDoubleClick(
    grid.ref,
    grid.isReady,
    useCallback(
      (cell) => {
        const day = resolveDayFromCell(rows, cell);
        if (day) setDialogDay(day);
      },
      [rows],
    ),
  );

  return (
    <div id="app">
      <div className="demo-container">
        <div className="calendar-demo">
          <DataGrid ref={grid.ref} rows={rows} gridConfig={gridConfig} className="calendar-demo__grid" />
          <EventDialog
            day={dialogDay}
            onCancel={() => setDialogDay(null)}
            onSubmit={(event, day) => {
              const focused = grid.ref.current?.element?.focusedCell;
              pendingFocusRef.current = focused
                ? { position: { rowIndex: focused.rowIndex, colIndex: focused.colIndex } }
                : { day: day.date.getDate() };
              dispatch({ type: 'add-event', event, day });
              setDialogDay(null);
            }}
          />
        </div>
      </div>
    </div>
  );
}

// demos/vue/src/demos/calendar/Calendar.vue
<script setup lang="ts">
import type { DataGridElement, GridConfig } from '@toolbox-web/grid';
import { TbwGrid as DataGrid, TbwGridColumn as GridColumn } from '@toolbox-web/grid-vue';
import '@toolbox-web/grid-vue/features/pinned-rows';
import '@demo/shared/calendar/demo-styles.css';
import {
  buildWeeks,
  generateEvents,
  isoKey,
  WEEKDAY_FIELDS,
  WEEKDAY_HEADERS,
  WEEKDAY_HEADERS_FULL,
  WEEKDAY_HEADERS_MINI,
  type CalendarDay,
  type CalendarEvent,
  type CalendarWeek,
  type WeekdayField,
} from '@demo/shared/calendar';
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, shallowRef, watch } from 'vue';
import DayCell from './components/DayCell.vue';
import EventDialog from './components/EventDialog.vue';
import HeaderNav from './components/HeaderNav.vue';
import Legend from './components/Legend.vue';
import ToolbarNav from './components/ToolbarNav.vue';
import { DEFAULT_ROW_HEIGHT_PX, useDynamicRowHeight } from './composables/useDynamicRowHeight';
import { useDoubleClick } from './composables/useDoubleClick';
import { useGridCallbackRoot } from './composables/useGridCallbackRoot';
import {
  findDayPosition,
  shiftCalendarMonth,
  useKeyboardNav,
  type CalendarViewState,
} from './composables/useKeyboardNav';

interface GridComponentExpose {
  gridElement: DataGridElement<CalendarWeek> | null;
  ready: () => Promise<void>;
}

const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
] as const;
const YEAR_RANGE = 5;

const today = new Date();
const state = reactive<CalendarViewState>({ year: today.getFullYear(), month: today.getMonth() });
const userEvents = reactive(new Map<string, CalendarEvent[]>()) as Map<string, CalendarEvent[]>;
const dialogDay = ref<CalendarDay | null>(null);
const gridComponent = ref<GridComponentExpose | null>(null);
const cleanups: (() => void)[] = [];
let rowHeightController: { apply: () => void; cleanup: () => void } | null = null;

const years = computed(() => {
  const currentYear = new Date().getFullYear();
  const out: number[] = [];
  for (let y = currentYear - YEAR_RANGE; y <= currentYear + YEAR_RANGE; y++) out.push(y);
  return out;
});

const rows = computed(() => makeRows(state, userEvents));

const headerRoot = useGridCallbackRoot(HeaderNav, () => ({
  state,
  years: years.value,
  monthNames: MONTH_NAMES,
  onYearChange: (year: number) => {
    state.year = year;
    rerender();
  },
}));

const toolbarRoot = useGridCallbackRoot(ToolbarNav, () => ({
  onPrev: () => shiftMonth(-1),
  onToday: goToday,
  onNext: () => shiftMonth(1),
}));

const legendRoot = useGridCallbackRoot(Legend, () => ({}));
// Cache the legend element so the pinned-rows plugin can short-circuit DOM
// mutation across grid renders (fresh element each call = unmount loop).
let legendElement: HTMLElement | null = null;

const gridConfig = shallowRef({
  fitMode: 'stretch',
  shell: { header: { toolPanelToggle: false } },
  rowHeight: DEFAULT_ROW_HEIGHT_PX,
  features: {
    pinnedRows: {
      slots: [
        {
          id: 'calendar-legend',
          position: 'bottom',
          render: () => {
            if (!legendElement) legendElement = legendRoot.mountElement('cal-legend-root');
            return legendElement;
          },
        },
      ],
    },
  },
} as GridConfig<CalendarWeek>);

function makeRows(viewState: CalendarViewState, addedEvents: ReadonlyMap<string, CalendarEvent[]>): CalendarWeek[] {
  const generated = generateEvents(viewState.year, viewState.month);
  const byDate = new Map(generated.byDate);
  for (const [key, events] of addedEvents) {
    const merged = [...(byDate.get(key) ?? []), ...events];
    merged.sort((a, b) => a.startTime.localeCompare(b.startTime));
    byDate.set(key, merged);
  }
  return buildWeeks(viewState.year, viewState.month, byDate);
}

function getGrid(): DataGridElement<CalendarWeek> | null {
  return gridComponent.value?.gridElement ?? null;
}

function patchGridConfig(patch: Partial<GridConfig<CalendarWeek>>): void {
  gridConfig.value = { ...gridConfig.value, ...patch } as GridConfig<CalendarWeek>;
}

function setState(next: CalendarViewState): void {
  state.year = next.year;
  state.month = next.month;
}

function rerender(focusTarget?: { day: number } | { position: { rowIndex: number; colIndex: number } }): void {
  rowHeightController?.apply();
  const grid = getGrid();
  if (!grid || !focusTarget) return;

  let target: { rowIndex: number; colIndex: number } | null = null;
  if ('day' in focusTarget) {
    target = findDayPosition(rows.value, state.year, state.month, focusTarget.day);
  } else {
    target = {
      rowIndex: Math.min(focusTarget.position.rowIndex, Math.max(rows.value.length - 1, 0)),
      colIndex: focusTarget.position.colIndex,
    };
  }

  if (target) {
    const focusTargetPosition = target;
    queueMicrotask(() => grid.focusCell?.(focusTargetPosition.rowIndex, focusTargetPosition.colIndex));
  }
}

function shiftMonth(delta: number): void {
  setState(shiftCalendarMonth(state, delta));
  rerender();
}

function goToday(): void {
  const now = new Date();
  state.year = now.getFullYear();
  state.month = now.getMonth();
  rerender({ day: now.getDate() });
}

function openDialog(day: CalendarDay): void {
  dialogDay.value = day;
}

function closeDialog(): void {
  dialogDay.value = null;
}

function addEvent(event: CalendarEvent, day: CalendarDay): void {
  const key = isoKey(day.date);
  const merged = [...(userEvents.get(key) ?? []), event];
  merged.sort((a, b) => a.startTime.localeCompare(b.startTime));
  userEvents.set(key, merged);
  closeDialog();

  const focused = getGrid()?.focusedCell;
  rerender(
    focused ? { position: { rowIndex: focused.rowIndex, colIndex: focused.colIndex } } : { day: day.date.getDate() },
  );
}

onMounted(async () => {
  await nextTick();
  const grid = getGrid();
  if (!grid) return;
  await grid.ready?.();

  grid.registerHeaderContent?.({ id: 'calendar-nav', order: 0, render: headerRoot.mount });
  grid.registerToolbarContent?.({ id: 'calendar-nav-buttons', order: 0, render: toolbarRoot.mount });
  grid.refreshShellHeader?.();
  // Vue's slot-mounted <TbwGridColumn> children don't trigger the grid's
  // column-template recompute on first mount; nudge it so layout uses the
  // configured column widths instead of collapsing to one column.
  grid.refreshColumns?.();
  grid.updateTemplate?.();

  cleanups.push(
    useKeyboardNav({
      grid,
      getRows: () => rows.value,
      getState: () => ({ year: state.year, month: state.month }),
      setState,
      rerender,
      openDialog,
    }),
    useDoubleClick(grid, openDialog),
  );

  rowHeightController = useDynamicRowHeight({ grid, getRows: () => rows.value, patchGridConfig });
  cleanups.push(rowHeightController.cleanup);
});

watch(
  () => rows.value.length,
  () => {
    void nextTick(() => rowHeightController?.apply());
  },
);

onBeforeUnmount(() => {
  const grid = getGrid();
  grid?.unregisterHeaderContent?.('calendar-nav');
  grid?.unregisterToolbarContent?.('calendar-nav-buttons');
  for (const cleanup of cleanups.splice(0)) cleanup();
  headerRoot.cleanupAll();
  toolbarRoot.cleanupAll();
  legendRoot.cleanupAll();
});
</script>

<template>
  <div class="demo-container">
    <div class="calendar-demo">
      <DataGrid ref="gridComponent" :rows="rows" :grid-config="gridConfig" class="calendar-demo__grid">
        <GridColumn field="weekNumber" header="W" :width="44" :sortable="false" :resizable="false" />
        <GridColumn
          v-for="field in WEEKDAY_FIELDS"
          :key="field"
          :field="field"
          :header="WEEKDAY_HEADERS_FULL[field]"
          :min-width="60"
          :sortable="false"
          :resizable="false"
        >
          <template #headerLabel>
            <span class="cal-wday">
              <span class="cal-wday__full">{{ WEEKDAY_HEADERS_FULL[field] }}</span>
              <span class="cal-wday__short">{{ WEEKDAY_HEADERS[field] }}</span>
              <span class="cal-wday__mini">{{ WEEKDAY_HEADERS_MINI[field] }}</span>
            </span>
          </template>
          <template #cell="{ value }">
            <DayCell :day="value" />
          </template>
        </GridColumn>
      </DataGrid>
      <EventDialog :day="dialogDay" @submit="addEvent" @close="closeDialog" />
    </div>
  </div>
</template>
