// demos/vue/src/demos/calendar/components/Legend.vue
<script setup lang="ts">
import { CATEGORIES } from '@demo/shared/calendar';
</script>

<template>
  <div class="cal-legend">
    <span v-for="category in CATEGORIES" :key="category.id" class="cal-legend__item">
      <span class="cal-legend__swatch" :style="{ background: `var(--cal-cat-${category.id})` }"></span>
      <span>{{ category.label }}</span>
    </span>
  </div>
</template>

// demos/react/src/demos/calendar/components/Legend.tsx
import { CATEGORIES, type CategoryId } from '@demo/shared/calendar';

export function Legend() {
  return (
    <div className="cal-legend">
      {CATEGORIES.map((category: { id: CategoryId; label: string }) => (
        <span key={category.id} className="cal-legend__item">
          <span className="cal-legend__swatch" style={{ background: `var(--cal-cat-${category.id})` }} />
          <span>{category.label}</span>
        </span>
      ))}
    </div>
  );
}
