// demos/vue/src/demos/calendar/components/ToolbarNav.vue
<script setup lang="ts">
defineProps<{
  onPrev: () => void;
  onToday: () => void;
  onNext: () => void;
}>();
</script>

<template>
  <div class="cal-toolbar-nav">
    <button type="button" class="cal-header__btn" title="Previous month" aria-label="Previous month" @click="onPrev">
      ‹
    </button>
    <button type="button" class="cal-header__btn" title="Jump to current month" aria-label="Jump to current month" @click="onToday">
      Today
    </button>
    <button type="button" class="cal-header__btn" title="Next month" aria-label="Next month" @click="onNext">
      ›
    </button>
  </div>
</template>

// demos/react/src/demos/calendar/components/ToolbarNav.tsx
export interface ToolbarNavProps {
  onPrevious: () => void;
  onToday: () => void;
  onNext: () => void;
}

export function ToolbarNav({ onPrevious, onToday, onNext }: ToolbarNavProps) {
  return (
    <div className="cal-toolbar-nav">
      <button type="button" className="cal-header__btn" aria-label="Previous month" title="Previous month" onClick={onPrevious}>
        ‹
      </button>
      <button type="button" className="cal-header__btn" aria-label="Jump to current month" title="Jump to current month" onClick={onToday}>
        Today
      </button>
      <button type="button" className="cal-header__btn" aria-label="Next month" title="Next month" onClick={onNext}>
        ›
      </button>
    </div>
  );
}
