// demos/vue/src/demos/employee-management/components/tool-panels/AnalyticsPanel.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Employee } from '@demo/shared/employee-management';
import { DEPARTMENTS } from '@demo/shared/employee-management';

/**
 * AnalyticsPanel - Sidebar panel showing employee analytics
 * Matches React: AnalyticsPanel.tsx
 */
const props = defineProps<{
  rows: Employee[];
}>();

const totalEmployees = computed(() => props.rows.length);

const avgSalary = computed(() => {
  if (props.rows.length === 0) return 0;
  const sum = props.rows.reduce((acc, row) => acc + row.salary, 0);
  return Math.round(sum / props.rows.length);
});

const avgRating = computed(() => {
  if (props.rows.length === 0) return 0;
  const sum = props.rows.reduce((acc, row) => acc + row.rating, 0);
  return (sum / props.rows.length).toFixed(1);
});

const topPerformers = computed(() => {
  return props.rows.filter((row) => row.isTopPerformer).length;
});

const departmentBreakdown = computed(() => {
  const breakdown: Record<string, number> = {};
  for (const dept of DEPARTMENTS) {
    breakdown[dept] = props.rows.filter((row) => row.department === dept).length;
  }
  return breakdown;
});

const statusBreakdown = computed(() => {
  const breakdown: Record<string, number> = {};
  for (const row of props.rows) {
    breakdown[row.status] = (breakdown[row.status] || 0) + 1;
  }
  return breakdown;
});

const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
};

const getPercentage = (count: number) => {
  if (totalEmployees.value === 0) return '0%';
  return `${Math.round((count / totalEmployees.value) * 100)}%`;
};
</script>

<template>
  <div class="analytics-panel">
    <div class="panel-header">
      <h3>Analytics</h3>
    </div>

    <div class="stats-section">
      <div class="stat-card">
        <span class="stat-value">{{ totalEmployees }}</span>
        <span class="stat-label">Total Employees</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{{ formatCurrency(avgSalary) }}</span>
        <span class="stat-label">Avg Salary</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{{ avgRating }}</span>
        <span class="stat-label">Avg Rating</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">{{ topPerformers }}</span>
        <span class="stat-label">Top Performers</span>
      </div>
    </div>

    <div class="breakdown-section">
      <h4>By Department</h4>
      <div class="breakdown-list">
        <div v-for="(count, dept) in departmentBreakdown" :key="dept" class="breakdown-item">
          <span class="breakdown-label">{{ dept }}</span>
          <span class="breakdown-value">{{ count }} ({{ getPercentage(count) }})</span>
        </div>
      </div>
    </div>

    <div class="breakdown-section">
      <h4>By Status</h4>
      <div class="breakdown-list">
        <div v-for="(count, status) in statusBreakdown" :key="status" class="breakdown-item">
          <span class="breakdown-label">{{ status }}</span>
          <span class="breakdown-value">{{ count }} ({{ getPercentage(count) }})</span>
        </div>
      </div>
    </div>
  </div>
</template>

// demos/employee-management/react/src/components/tool-panels/AnalyticsPanel.tsx
import type { Employee } from '@demo/shared/employee-management';
import type { ToolPanelContext } from '@toolbox-web/grid-react';
import { useEffect, useMemo, useState } from 'react';

interface AnalyticsPanelProps {
  grid: ToolPanelContext['grid'];
}

interface DepartmentData {
  name: string;
  count: number;
  percentage: number;
}

export function AnalyticsPanel({ grid }: AnalyticsPanelProps) {
  const [rows, setRows] = useState<Employee[]>([]);

  useEffect(() => {
    // Get rows from grid
    if (grid.rows) {
      setRows([...grid.rows] as Employee[]);
    }

    // Listen for data changes
    const handleDataChange = () => {
      if (grid.rows) {
        setRows([...grid.rows] as Employee[]);
      }
    };

    const unsubData = grid.on('data-change', handleDataChange);
    const unsubFilter = grid.on('filter-change', handleDataChange);

    return () => {
      unsubData();
      unsubFilter();
    };
  }, [grid]);

  // Computed values matching Angular/Vanilla
  const totalSalary = useMemo(() => rows.reduce((sum, r) => sum + (r.salary || 0), 0), [rows]);
  const avgSalary = useMemo(() => (rows.length > 0 ? totalSalary / rows.length : 0), [totalSalary, rows.length]);
  const avgRating = useMemo(() => {
    if (rows.length === 0) return 0;
    return rows.reduce((sum, r) => sum + (r.rating || 0), 0) / rows.length;
  }, [rows]);
  const topPerformers = useMemo(() => rows.filter((r) => r.isTopPerformer).length, [rows]);

  const departmentCounts = useMemo((): DepartmentData[] => {
    const counts: Record<string, number> = {};
    rows.forEach((r) => {
      counts[r.department] = (counts[r.department] || 0) + 1;
    });
    return Object.entries(counts)
      .map(([name, count]) => ({
        name,
        count,
        percentage: rows.length > 0 ? (count / rows.length) * 100 : 0,
      }))
      .sort((a, b) => b.count - a.count);
  }, [rows]);

  const topDepartments = useMemo(() => departmentCounts.slice(0, 6), [departmentCounts]);
  const largestDept = useMemo(() => departmentCounts[0] || null, [departmentCounts]);

  const formatCurrency = (value: number) => {
    return value.toLocaleString('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    });
  };

  return (
    <div className="analytics-content">
      <div className="stat-cards">
        <div className="stat-card stat-card--payroll">
          <div className="stat-card__label">Total Payroll</div>
          <div className="stat-card__value">{formatCurrency(totalSalary)}</div>
        </div>
        <div className="stat-card stat-card--salary">
          <div className="stat-card__label">Avg Salary</div>
          <div className="stat-card__value">{formatCurrency(avgSalary)}</div>
        </div>
        <div className="stat-card stat-card--rating">
          <div className="stat-card__label">Avg Rating</div>
          <div className="stat-card__value">{avgRating.toFixed(1)} ★</div>
        </div>
        <div className="stat-card stat-card--performers">
          <div className="stat-card__label">Top Performers</div>
          <div className="stat-card__value">{topPerformers}</div>
        </div>
      </div>

      <div className="dept-distribution">
        <h4 className="dept-distribution__title">Department Distribution</h4>
        <div className="dept-bars">
          {topDepartments.map((dept) => (
            <div key={dept.name} className="dept-bar">
              <span className="dept-bar__name" title={dept.name}>
                {dept.name}
              </span>
              <div className="dept-bar__track">
                <div className="dept-bar__fill" style={{ width: `${dept.percentage}%` }} />
              </div>
              <span className="dept-bar__count">{dept.count}</span>
            </div>
          ))}
        </div>
      </div>

      {largestDept && (
        <div className="largest-dept">
          <div className="largest-dept__label">Largest Department</div>
          <div className="largest-dept__value">
            {largestDept.name}
            <span className="largest-dept__count">({largestDept.count} employees)</span>
          </div>
        </div>
      )}
    </div>
  );
}
