// demos/employee-management/angular/src/app/renderers/status-badge.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-status-badge',
  template: `<span class="status-badge" [class]="badgeClass()">{{ value() }}</span>`,
  styles: [],
})
export class StatusBadgeComponent {
  value = input<string>('');

  badgeClass = () => {
    const v = this.value();
    return v ? `status-badge--${v.toLowerCase().replace(/\s+/g, '-')}` : '';
  };
}

// demos/react/src/demos/employee-management/components/renderers/StatusBadge.tsx
/**
 * StatusBadge - Color-coded status badge renderer
 * Matches Angular: app-status-badge
 */
interface StatusBadgeProps {
  value: string;
}

export function StatusBadge({ value }: StatusBadgeProps) {
  const badgeClass = value ? `status-badge--${value.toLowerCase().replace(/\s+/g, '-')}` : '';

  return <span className={`status-badge ${badgeClass}`}>{value}</span>;
}
