// demos/react/src/demos/employee-management/components/renderers/StatusBadge.tsx
/**
 * StatusBadge - Color-coded status badge renderer
 * Matches Angular: app-status-badge
 */
interface StatusBadgeProps {
  value: string;
}

export function StatusBadge({ value }: StatusBadgeProps) {
  const badgeClass = value ? `status-badge--${value.toLowerCase().replace(/\s+/g, '-')}` : '';

  return <span className={`status-badge ${badgeClass}`}>{value}</span>;
}

// demos/vue/src/demos/employee-management/components/renderers/StatusBadge.vue
<script setup lang="ts">
/**
 * StatusBadge - Color-coded status badge renderer
 * Matches React: StatusBadge.tsx
 */
defineProps<{
  value: string;
}>();
</script>

<template>
  <span :class="['status-badge', value ? `status-badge--${value.toLowerCase().replace(/\s+/g, '-')}` : '']">
    {{ value }}
  </span>
</template>
