// demos/employee-management/react/src/components/renderers/TopPerformerStar.tsx
/**
 * TopPerformerStar - Star indicator for top performers
 * Matches Angular: app-top-performer
 */
interface TopPerformerStarProps {
  value: boolean;
}

export function TopPerformerStar({ value }: TopPerformerStarProps) {
  const className = `top-performer-star ${value ? 'top-performer-star--active' : 'top-performer-star--inactive'}`;

  return <span className={className}>{value ? '★' : '☆'}</span>;
}

// demos/vue/src/demos/employee-management/components/renderers/TopPerformerStar.vue
<script setup lang="ts">
/**
 * TopPerformerStar - Star indicator for top performers
 * Matches React: TopPerformerStar.tsx
 */
defineProps<{
  value: boolean;
}>();
</script>

<template>
  <span :class="['top-performer-star', value ? 'top-performer-star--active' : 'top-performer-star--inactive']">{{
    value ? '★' : '☆'
  }}</span>
</template>
