// demos/angular/src/demos/employee-management/employee-management.component.ts
// Feature imports for the directives wired in this component's `imports` array
// (events the demo subscribes to). All other feature side-effect imports live
// next to the matching `gridConfig.features` keys in `./grid-config.ts`.
import '@toolbox-web/grid-angular/features/editing';
import '@toolbox-web/grid-angular/features/filtering';
// Master-detail and responsive must be side-effect-imported in the component
// so their `<tbw-grid-detail>` / `<tbw-grid-responsive-card>` template elements
// get wired into the corresponding plugin's renderer in ngAfterContentInit.
import '@toolbox-web/grid-angular/features/master-detail';
import '@toolbox-web/grid-angular/features/responsive';

import { CurrencyPipe } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { generateEmployees, type Employee } from '@demo/shared/employee-management';
import { shadowDomStyles } from '@demo/shared/employee-management/styles';
import {
  CellCommitEvent,
  Grid,
  injectGrid,
  TbwGridColumn,
  TbwGridHeader,
  TbwGridToolButtons,
  TbwRenderer,
} from '@toolbox-web/grid-angular';
import {
  GridEditingDirective,
  GridLazyForm,
  TbwEditor,
} from '@toolbox-web/grid-angular/features/editing';
import { injectGridExport } from '@toolbox-web/grid-angular/features/export';
import { GridFilteringDirective } from '@toolbox-web/grid-angular/features/filtering';
import { GridDetailView } from '@toolbox-web/grid-angular/features/master-detail';
import { GridResponsiveCard } from '@toolbox-web/grid-angular/features/responsive';
import { GridToolPanel } from '@toolbox-web/grid-angular/features/shell';
import { createGridConfig } from './grid-config';

// Import components so they're available in templates
// Note: RatingDisplayComponent and StarRatingEditorComponent are configured via gridConfig,
// not imported here (they use component-class column config instead of templates)
import { BonusSliderEditorComponent } from './editors/bonus-slider-editor.component';
import { DateEditorComponent } from './editors/date-editor.component';
import { StatusSelectEditorComponent } from './editors/status-select-editor.component';
import { DetailPanelComponent } from './renderers/detail-panel.component';
import { StatusBadgeComponent } from './renderers/status-badge.component';
import { TopPerformerComponent } from './renderers/top-performer.component';
import { AnalyticsPanelComponent, QuickFiltersPanelComponent } from './tool-panels';

@Component({
  selector: 'app-employee-management',
  imports: [
    CurrencyPipe,
    FormsModule,
    ReactiveFormsModule,
    Grid,
    GridDetailView,
    GridFilteringDirective,
    GridEditingDirective,
    GridLazyForm,
    GridResponsiveCard,
    GridToolPanel,
    TbwGridColumn,
    TbwGridHeader,
    TbwGridToolButtons,
    TbwRenderer,
    TbwEditor,
    // Renderer components (RatingDisplayComponent is configured in gridConfig instead)
    StatusBadgeComponent,
    TopPerformerComponent,
    DetailPanelComponent,
    // Editor components (StarRatingEditorComponent is configured in gridConfig instead)
    StatusSelectEditorComponent,
    BonusSliderEditorComponent,
    DateEditorComponent,
    // Tool panel components
    QuickFiltersPanelComponent,
    AnalyticsPanelComponent,
  ],
  templateUrl: './employee-management.component.html',
})
export class EmployeeManagementComponent {
  private fb = inject(FormBuilder);

  rowCount = signal(200);
  enableSelection = signal(true);
  enableFiltering = signal(true);
  enableSorting = signal(true);
  enableEditing = signal(true);
  enableMasterDetail = signal(true);

  // Custom styles for shadow DOM (editors, renderers, detail panels)
  // The Grid directive automatically injects these into the grid's shadow DOM
  customStyles = shadowDomStyles;

  // Generate employee data - recomputed when rowCount changes
  rows = computed(() => generateEmployees(this.rowCount()));

  /**
   * Lazy form factory - creates a FormGroup only when a row enters edit mode.
   * This is ~20-100x more efficient than creating FormGroups for all rows upfront!
   *
   * For 200 rows with 22 fields, the old approach created 4,400 FormControls.
   * This approach creates ~10 FormControls (only for the row being edited).
   */
  createRowForm = (employee: Employee): FormGroup =>
    this.fb.group({
      // Only include EDITABLE fields - no need for disabled read-only fields
      firstName: [employee.firstName, Validators.required],
      lastName: [employee.lastName, Validators.required],
      department: [employee.department],
      title: [employee.title],
      level: [employee.level, [Validators.min(1), Validators.max(10)]],
      salary: [employee.salary, [Validators.required, Validators.min(0)]],
      bonus: [employee.bonus, [Validators.min(0), Validators.max(100)]],
      status: [employee.status],
      hireDate: [employee.hireDate],
      rating: [employee.rating, [Validators.min(0), Validators.max(5)]],
    });

  // Grid config - recomputed when feature flags change
  gridConfig = computed(() =>
    createGridConfig({
      enableSelection: this.enableSelection(),
      enableFiltering: this.enableFiltering(),
      enableSorting: this.enableSorting(),
      enableEditing: this.enableEditing(),
      enableMasterDetail: this.enableMasterDetail(),
    }),
  );

  // Typed grid access via injectGrid - cleaner than viewChild!
  grid = injectGrid<Employee>();

  // Feature-scoped hook for export functionality
  gridExport = injectGridExport();

  exportCsv(): void {
    this.gridExport.exportToCsv('employees.csv');
  }

  exportExcel(): void {
    this.gridExport.exportToExcel('employees.xlsx');
  }

  /**
   * Handle cell commit events at the grid level.
   * This demonstrates the event bubbling feature - instead of handling
   * commit in each editor template, we can handle it centrally here.
   */
  onCellCommit(event: CellCommitEvent): void {
    console.log(`[Grid] Cell committed: ${event.field} = ${event.value} (row ${event.rowIndex})`);
    // Example: could trigger auto-save, show notification, etc.
  }

  /**
   * Filter-change handler wired via `(filterChange)` on <tbw-grid>. Owned by
   * `GridFilteringDirective` from `@toolbox-web/grid-angular/features/filtering`,
   * which is added to this component's `imports` above. Without that import
   * Angular's compiler would error with `Can't bind to 'filterChange'...`.
   */
  onFilterChange(event: unknown): void {
    console.log('[Grid] filter-change', event);
  }

  /**
   * Get department color for responsive card avatar.
   */
  getDepartmentColor(department: string): string {
    const colors: Record<string, string> = {
      Engineering: '#3b82f6',
      Marketing: '#ec4899',
      Sales: '#f59e0b',
      HR: '#10b981',
      Finance: '#6366f1',
      Legal: '#8b5cf6',
      Operations: '#14b8a6',
      'Customer Support': '#f97316',
    };
    return colors[department] ?? '#6b7280';
  }
}

<div class="demo-container">
  <header class="demo-header">
    <div class="demo-controls">
      <label>
        <span class="row-count-display">
          Rows: <strong>{{ rowCount() }}</strong>
        </span>
        <input type="range" [(ngModel)]="rowCount" min="50" max="1000" step="50" />
      </label>
      <label>
        <input type="checkbox" [(ngModel)]="enableSelection" />
        Selection
      </label>
      <label>
        <input type="checkbox" [(ngModel)]="enableFiltering" />
        Filtering
      </label>
      <label>
        <input type="checkbox" [(ngModel)]="enableSorting" />
        Sorting
      </label>
      <label>
        <input type="checkbox" [(ngModel)]="enableEditing" />
        Editing
      </label>
      <label>
        <input type="checkbox" [(ngModel)]="enableMasterDetail" />
        Master-Detail
      </label>
    </div>
  </header>

  <div class="grid-wrapper">
    <div class="demo-grid">
      <!--
        Feature configuration lives entirely in `gridConfig.features` (see
        `grid-config.ts`). Only event-bearing directives are wired here:
          - GridEditingDirective   -> (cellCommit)
          - GridFilteringDirective -> (filterChange)
        The directives still attach (their selectors match the event bindings)
        but do not own feature config.
      -->
      <tbw-grid
        #grid
        id="employee-grid"
        [rows]="rows()"
        [lazyForm]="createRowForm"
        [gridConfig]="gridConfig()"
        [customStyles]="customStyles"
        (cellCommit)="onCellCommit($event)"
        (filterChange)="onFilterChange($event)"
      >
        <!-- Shell configuration with title -->
        <tbw-grid-header title="Employee Management System (Angular)"></tbw-grid-header>

        <!-- Toolbar buttons container -->
        <tbw-grid-tool-buttons>
          <button
            class="tbw-toolbar-btn"
            title="Export CSV"
            aria-label="Export CSV"
            (click)="exportCsv()"
          >
            📄
          </button>
          <button
            class="tbw-toolbar-btn"
            title="Export Excel"
            aria-label="Export Excel"
            (click)="exportExcel()"
          >
            📊
          </button>
        </tbw-grid-tool-buttons>

        <!-- Column templates - column definitions come from gridConfig, these add Angular templates -->
        <!-- Using structural directives for cleaner syntax -->
        <!-- Auto-wiring: editor components just emit (commit) and (cancel) events, no explicit binding needed -->
        <!-- The 'control' variable provides access to the FormControl from the FormArray binding -->
        <!-- When control is provided, the editor derives value from control.value automatically -->
        <tbw-grid-column field="status">
          <app-status-badge *tbwRenderer="let value" [value]="value" />
          @if (enableEditing()) {
            <app-status-select-editor *tbwEditor="let _; control as control" [control]="control" />
          }
        </tbw-grid-column>
        <tbw-grid-column field="bonus">
          @if (enableEditing()) {
            <app-bonus-slider-editor
              *tbwEditor="let value; row as row"
              [value]="value"
              [salary]="row.salary"
            />
          }
        </tbw-grid-column>
        <!-- Rating column uses component-class config in gridConfig instead of templates -->
        <!-- See grid-config.ts: { field: 'rating', renderer: RatingDisplayComponent, editor: StarRatingEditorComponent } -->
        <tbw-grid-column field="hireDate">
          @if (enableEditing()) {
            <app-date-editor *tbwEditor="let value" [value]="value" />
          }
        </tbw-grid-column>
        <tbw-grid-column field="isTopPerformer">
          <app-top-performer *tbwRenderer="let value" [value]="value" />
        </tbw-grid-column>

        <!-- Master-detail template -->
        @if (enableMasterDetail()) {
          <tbw-grid-detail [showExpandColumn]="true" animation="slide">
            <ng-template let-row>
              <app-detail-panel [employee]="row" />
            </ng-template>
          </tbw-grid-detail>
        }

        <!-- Responsive card template for mobile/narrow layouts -->
        <tbw-grid-responsive-card>
          <ng-template let-emp let-idx="index">
            <div class="responsive-employee-card">
              <div
                class="responsive-employee-card__avatar"
                [style.background-color]="getDepartmentColor(emp.department)"
              >
                {{ emp.firstName.charAt(0) }}{{ emp.lastName.charAt(0) }}
              </div>
              <div class="responsive-employee-card__content">
                <div class="responsive-employee-card__header">
                  <span class="responsive-employee-card__name"
                    >{{ emp.firstName }} {{ emp.lastName }}</span
                  >
                  <app-status-badge [value]="emp.status" />
                </div>
                <div class="responsive-employee-card__title">{{ emp.title }}</div>
                <div class="responsive-employee-card__meta">
                  <span
                    class="responsive-employee-card__dept"
                    [style.color]="getDepartmentColor(emp.department)"
                    >{{ emp.department }}</span
                  >
                  <span class="responsive-employee-card__separator">•</span>
                  <span class="responsive-employee-card__salary">{{
                    emp.salary | currency: 'USD' : 'symbol' : '1.0-0'
                  }}</span>
                  <span class="responsive-employee-card__separator">•</span>
                  <span class="responsive-employee-card__rating"
                    >{{ emp.rating.toFixed(1) }} ★</span
                  >
                  @if (emp.isTopPerformer) {
                    <span class="responsive-employee-card__top-performer">⭐</span>
                  }
                </div>
              </div>
            </div>
          </ng-template>
        </tbw-grid-responsive-card>

        <!-- Custom Tool Panels -->
        <tbw-grid-tool-panel
          id="quick-filters"
          title="Quick Filters"
          icon="🔍"
          tooltip="Apply quick filters to the data"
          [order]="10"
        >
          <ng-template let-grid>
            <app-quick-filters-panel [grid]="grid" />
          </ng-template>
        </tbw-grid-tool-panel>

        <tbw-grid-tool-panel
          id="analytics"
          title="Analytics"
          icon="📈"
          tooltip="View data analytics and insights"
          [order]="20"
        >
          <ng-template let-grid>
            <app-analytics-panel [grid]="grid" [rows]="rows()" />
          </ng-template>
        </tbw-grid-tool-panel>
      </tbw-grid>
    </div>
  </div>
</div>

// demos/vue/src/demos/employee-management/EmployeeManagement.vue
<script setup lang="ts">
/**
 * Employee Management Demo - Vue 3 Implementation
 *
 * This demo showcases @toolbox-web/grid-vue best practices:
 * - Feature imports for tree-shakeable plugin loading (side-effect imports)
 * - Feature props for declarative plugin configuration
 * - Event handling via @event-name syntax
 * - GridConfig for inline Vue renderers/editors
 * - TbwGridDetailPanel for declarative master-detail panels
 * - TbwGridToolPanel for custom sidebar panels
 * - TbwGridToolButtons for toolbar actions
 * - TbwGridResponsiveCard for responsive card layouts
 * - useGrid() composable for programmatic access
 * - TypeScript generics for row type safety
 *
 * The grid matches visual design and functionality across all framework demos.
 *
 * NOTE: Feature side-effect imports (`@toolbox-web/grid-vue/features/*`) live
 * next to the configuration in `./grid-config.ts`, since that's where the
 * matching `gridConfig.features` keys are declared.
 */

import {
  TbwGrid,
  TbwGridDetailPanel,
  TbwGridResponsiveCard,
  TbwGridToolButtons,
  TbwGridToolPanel,
  useGrid,
} from '@toolbox-web/grid-vue';
import { useGridExport } from '@toolbox-web/grid-vue/features/export';
import { computed, h, markRaw, ref } from 'vue';

// Import shared data, types, and styles
import { generateEmployees, type Employee } from '@demo/shared/employee-management';
import '@demo/shared/employee-management/demo-styles.css';

// Grid configuration (columns, groups, pinned rows, responsive, features)
import { createGridConfig } from './grid-config';

// Vue-specific renderers and editors
import BonusSliderEditor from './components/editors/BonusSliderEditor.vue';
import DateEditor from './components/editors/DateEditor.vue';
import StarRatingEditor from './components/editors/StarRatingEditor.vue';
import StatusSelectEditor from './components/editors/StatusSelectEditor.vue';
import DetailPanel from './components/renderers/DetailPanel.vue';
import RatingDisplay from './components/renderers/RatingDisplay.vue';
import ResponsiveEmployeeCard from './components/renderers/ResponsiveEmployeeCard.vue';
import StatusBadge from './components/renderers/StatusBadge.vue';
import TopPerformerStar from './components/renderers/TopPerformerStar.vue';
import AnalyticsPanel from './components/tool-panels/AnalyticsPanel.vue';
import QuickFiltersPanel from './components/tool-panels/QuickFiltersPanel.vue';

// ═══════════════════════════════════════════════════════════════════════════════
// STATE
// ═══════════════════════════════════════════════════════════════════════════════
const rowCount = ref(200);
const employees = ref<Employee[]>(generateEmployees(rowCount.value));

// Demo options - toggle features dynamically
const enableSelection = ref(true);
const enableFiltering = ref(true);
const enableSorting = ref(true);
const enableEditing = ref(true);
const enableMasterDetail = ref(true);

// useGrid() composable for programmatic access
const { gridElement } = useGrid<Employee>();

// useGridExport() for clean export API
const { exportToCsv, exportToExcel } = useGridExport<Employee>();

// ═══════════════════════════════════════════════════════════════════════════════
// HANDLERS
// ═══════════════════════════════════════════════════════════════════════════════
const handleRowCountChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  const newCount = parseInt(target.value, 10);
  rowCount.value = newCount;
  employees.value = generateEmployees(newCount);
};

// ═══════════════════════════════════════════════════════════════════════════════
// RENDERERS & EDITORS - Define outside computed to avoid recreating on each render
// ═══════════════════════════════════════════════════════════════════════════════

// Stable renderer functions that won't cause infinite loops
const renderers = {
  status: (value: string) => h(StatusBadge, { value }),
  rating: (value: number) => h(RatingDisplay, { value }),
  topPerformer: (value: boolean) => h(TopPerformerStar, { value }),
};

// Stable editor functions
const editors = {
  bonus: (value: number, salary: number, commit: (v: number) => void, cancel: () => void) =>
    h(BonusSliderEditor, { value, onCommit: commit, onCancel: cancel }),
  status: (value: string, commit: (v: string) => void, cancel: () => void) =>
    h(StatusSelectEditor, { value, onCommit: commit, onCancel: cancel }),
  date: (value: string, commit: (v: string) => void, cancel: () => void) =>
    h(DateEditor, { value, onCommit: commit, onCancel: cancel }),
  rating: (value: number, commit: (v: number) => void, cancel: () => void) =>
    h(StarRatingEditor, { value, onCommit: commit, onCancel: cancel }),
};

// ═══════════════════════════════════════════════════════════════════════════════
// GRID CONFIG
// ═══════════════════════════════════════════════════════════════════════════════

// Use markRaw to prevent Vue from deeply tracking the config object.
// This avoids infinite reactivity loops when the grid's internal state changes.
const gridConfig = computed(() =>
  markRaw(
    createGridConfig({
      enableSelection: enableSelection.value,
      enableFiltering: enableFiltering.value,
      enableSorting: enableSorting.value,
      enableEditing: enableEditing.value,
      enableMasterDetail: enableMasterDetail.value,
      renderers,
      editors,
    }),
  ),
);
</script>

<template>
  <div id="app">
    <div class="demo-container">
      <!-- Demo Controls Header -->
      <header class="demo-header">
        <div class="demo-controls">
          <label>
            <span class="row-count-display">
              Rows: <strong>{{ rowCount }}</strong>
            </span>
            <input type="range" min="50" max="1000" step="50" :value="rowCount" @input="handleRowCountChange" />
          </label>
          <label> <input type="checkbox" v-model="enableSelection" /> Selection </label>
          <label> <input type="checkbox" v-model="enableFiltering" /> Filtering </label>
          <label> <input type="checkbox" v-model="enableSorting" /> Sorting </label>
          <label> <input type="checkbox" v-model="enableEditing" /> Editing </label>
          <label> <input type="checkbox" v-model="enableMasterDetail" /> Master-Detail </label>
        </div>
      </header>

      <!-- Grid -->
      <div class="grid-wrapper">
        <TbwGrid :rows="employees" :gridConfig="gridConfig" class="demo-grid">
          <!-- Toolbar buttons -->
          <TbwGridToolButtons>
            <button
              class="tbw-toolbar-btn"
              title="Export CSV"
              aria-label="Export CSV"
              @click="exportToCsv('employees.csv')"
            >
              📄
            </button>
            <button
              class="tbw-toolbar-btn"
              title="Export Excel"
              aria-label="Export Excel"
              @click="exportToExcel('employees.xlsx')"
            >
              📊
            </button>
          </TbwGridToolButtons>

          <!-- Custom tool panels -->
          <TbwGridToolPanel id="quick-filters" title="Quick Filters" icon="🔍">
            <template #default="{ grid }">
              <QuickFiltersPanel @filter-change="(filters) => console.log('Filters:', filters)" />
            </template>
          </TbwGridToolPanel>

          <TbwGridToolPanel id="analytics" title="Analytics" icon="📈">
            <template #default="{ grid }">
              <AnalyticsPanel :rows="employees" />
            </template>
          </TbwGridToolPanel>

          <!-- Master-detail panel -->
          <TbwGridDetailPanel v-if="enableMasterDetail">
            <template #default="{ row }">
              <DetailPanel :row="row" />
            </template>
          </TbwGridDetailPanel>

          <!-- Responsive card for mobile/narrow layouts -->
          <TbwGridResponsiveCard>
            <template #default="{ row }">
              <ResponsiveEmployeeCard :row="row" />
            </template>
          </TbwGridResponsiveCard>
        </TbwGrid>
      </div>
    </div>
  </div>
</template>
