// demos/vue/src/demos/employee-management/components/editors/DateEditor.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';

/**
 * DateEditor - Date picker editor
 * Matches React: DateEditor.tsx
 */
const props = defineProps<{
  value: string;
}>();

const emit = defineEmits<{
  commit: [value: string];
  cancel: [];
}>();

const inputRef = ref<HTMLInputElement | null>(null);
const currentValue = ref(props.value || '');

watch(
  () => props.value,
  (newValue) => {
    currentValue.value = newValue || '';
  },
);

onMounted(() => {
  inputRef.value?.focus();
});

const handleChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit('commit', target.value);
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape') {
    emit('cancel');
  } else if (event.key === 'Enter') {
    emit('commit', currentValue.value);
  }
};
</script>

<template>
  <input
    ref="inputRef"
    type="date"
    :value="currentValue"
    class="date-editor"
    @change="handleChange"
    @keydown="handleKeyDown"
  />
</template>

// demos/employee-management/angular/src/app/editors/date-editor.component.ts
import { CommonModule } from '@angular/common';
import {
  AfterViewInit,
  Component,
  effect,
  ElementRef,
  input,
  output,
  viewChild,
} from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-date-editor',
  imports: [CommonModule, FormsModule],
  template: `
    <input
      #dateInput
      type="date"
      class="date-editor"
      [(ngModel)]="currentValueModel"
      (change)="onCommit()"
      (keydown)="onKeyDown($event)"
    />
  `,
  styles: [],
})
export class DateEditorComponent implements AfterViewInit {
  value = input<string>('');
  commit = output<string>();
  cancel = output<void>();
  dateInput = viewChild.required<ElementRef<HTMLInputElement>>('dateInput');

  currentValueModel = '';

  constructor() {
    effect(() => {
      this.currentValueModel = this.value() || '';
    });
  }

  ngAfterViewInit(): void {
    setTimeout(() => this.dateInput().nativeElement.focus(), 0);
  }

  onCommit(): void {
    this.commit.emit(this.currentValueModel);
  }

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.commit.emit(this.currentValueModel);
    } else if (event.key === 'Escape') {
      this.cancel.emit();
    }
  }
}
