// demos/vue/src/demos/employee-management/components/editors/StarRatingEditor.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';

/**
 * StarRatingEditor - Interactive 5-star rating editor with keyboard support
 * Matches React: StarRatingEditor.tsx
 */
const props = defineProps<{
  value: number;
}>();

const emit = defineEmits<{
  commit: [value: number];
  cancel: [];
}>();

const containerRef = ref<HTMLDivElement | null>(null);
const currentValue = ref(props.value ?? 3);
const stars = [1, 2, 3, 4, 5];

watch(
  () => props.value,
  (newValue) => {
    currentValue.value = newValue ?? 3;
  },
);

onMounted(() => {
  setTimeout(() => containerRef.value?.focus(), 0);
});

const handleStarClick = (star: number) => {
  currentValue.value = star;
  emit('commit', star);
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'ArrowLeft' && currentValue.value > 1) {
    currentValue.value = Math.max(1, currentValue.value - 0.5);
  } else if (event.key === 'ArrowRight' && currentValue.value < 5) {
    currentValue.value = Math.min(5, currentValue.value + 0.5);
  } else if (event.key === 'Enter') {
    emit('commit', currentValue.value);
  } else if (event.key === 'Escape') {
    emit('cancel');
  }
};

const getStarClass = (star: number) => {
  return star <= currentValue.value
    ? 'star-rating-editor__star star-rating-editor__star--filled'
    : 'star-rating-editor__star star-rating-editor__star--empty';
};
</script>

<template>
  <div ref="containerRef" class="star-rating-editor" tabindex="0" @keydown="handleKeyDown">
    <span v-for="star in stars" :key="star" :class="getStarClass(star)" @click="handleStarClick(star)">
      {{ star <= Math.round(currentValue) ? '★' : '☆' }}
    </span>
    <span class="star-rating-editor__label">{{ currentValue.toFixed(1) }}</span>
  </div>
</template>

// demos/employee-management/angular/src/app/editors/star-rating-editor.component.ts
import { CommonModule } from '@angular/common';
import {
  AfterViewInit,
  Component,
  effect,
  ElementRef,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';

@Component({
  selector: 'app-star-rating-editor',
  imports: [CommonModule],
  template: `
    <div class="star-rating-editor" #container tabindex="0" (keydown)="onKeyDown($event)">
      @for (star of stars; track star) {
        <span
          class="star-rating-editor__star"
          [class.star-rating-editor__star--filled]="star <= currentValue()"
          [class.star-rating-editor__star--empty]="star > currentValue()"
          (click)="onStarClick(star)"
        >
          {{ star <= Math.round(currentValue()) ? '★' : '☆' }}
        </span>
      }
      <span class="star-rating-editor__label">{{ currentValue().toFixed(1) }}</span>
    </div>
  `,
  styles: [],
})
export class StarRatingEditorComponent implements AfterViewInit {
  value = input<number>(3);
  commit = output<number>();
  cancel = output<void>();
  container = viewChild.required<ElementRef<HTMLDivElement>>('container');

  currentValue = signal(3);
  readonly stars = [1, 2, 3, 4, 5];
  readonly Math = Math;

  constructor() {
    effect(() => {
      this.currentValue.set(this.value() ?? 3);
    });
  }

  ngAfterViewInit(): void {
    setTimeout(() => this.container().nativeElement.focus(), 0);
  }

  onStarClick(star: number): void {
    this.currentValue.set(star);
    this.commit.emit(star);
  }

  onKeyDown(event: KeyboardEvent): void {
    const current = this.currentValue();
    if (event.key === 'ArrowLeft' && current > 1) {
      this.currentValue.set(Math.max(1, current - 0.5));
    } else if (event.key === 'ArrowRight' && current < 5) {
      this.currentValue.set(Math.min(5, current + 0.5));
    } else if (event.key === 'Enter') {
      this.commit.emit(this.currentValue());
    } else if (event.key === 'Escape') {
      this.cancel.emit();
    }
  }
}
