// demos/vue/src/demos/employee-management/components/editors/DateEditor.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';

/**
 * DateEditor - Date picker editor
 * Matches React: DateEditor.tsx
 */
const props = defineProps<{
  value: string;
}>();

const emit = defineEmits<{
  commit: [value: string];
  cancel: [];
}>();

const inputRef = ref<HTMLInputElement | null>(null);
const currentValue = ref(props.value || '');

watch(
  () => props.value,
  (newValue) => {
    currentValue.value = newValue || '';
  },
);

onMounted(() => {
  inputRef.value?.focus();
});

const handleChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit('commit', target.value);
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape') {
    emit('cancel');
  } else if (event.key === 'Enter') {
    emit('commit', currentValue.value);
  }
};
</script>

<template>
  <input
    ref="inputRef"
    type="date"
    :value="currentValue"
    class="date-editor"
    @change="handleChange"
    @keydown="handleKeyDown"
  />
</template>

// demos/react/src/demos/employee-management/components/editors/DateEditor.tsx
import { useEffect, useRef, useState } from 'react';

/**
 * DateEditor - Native HTML5 date input editor
 * Matches Angular: app-date-editor
 */
interface DateEditorProps {
  value: string;
  onCommit: (value: string) => void;
  onCancel: () => void;
}

export function DateEditor({ value, onCommit, onCancel }: DateEditorProps) {
  const [currentValue, setCurrentValue] = useState(value || '');
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    // Focus the input after mount
    setTimeout(() => inputRef.current?.focus(), 0);
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    setCurrentValue(newValue);
    onCommit(newValue);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      onCommit(currentValue);
    } else if (e.key === 'Escape') {
      onCancel();
    }
  };

  return (
    <input
      ref={inputRef}
      type="date"
      className="date-editor"
      value={currentValue}
      onChange={handleChange}
      onKeyDown={handleKeyDown}
    />
  );
}
