// demos/angular/src/demos/employee-management/editors/star-rating-editor.component.ts
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, effect, ElementRef, signal, viewChild } from '@angular/core';
import type { Employee } from '@demo/shared/employee-management';
import { BaseGridEditor } from '@toolbox-web/grid-angular/features/editing';

/**
 * Star rating editor extending BaseGridEditor.
 *
 * Demonstrates:
 * - Using currentValue() from base class
 * - Local signal for UI state
 * - Keyboard navigation
 */
@Component({
  selector: 'app-star-rating-editor',
  imports: [CommonModule],
  template: `
    <div class="star-rating-editor" #container tabindex="0" (keydown)="onKeyDown($event)">
      @for (star of stars; track star) {
        <span
          class="star-rating-editor__star"
          [class.star-rating-editor__star--filled]="star <= ratingValue()"
          [class.star-rating-editor__star--empty]="star > ratingValue()"
          (click)="onStarClick(star)"
        >
          {{ star <= Math.round(ratingValue()) ? '★' : '☆' }}
        </span>
      }
      <span class="star-rating-editor__label">{{ ratingValue().toFixed(1) }}</span>
    </div>
  `,
  styles: [],
})
export class StarRatingEditorComponent
  extends BaseGridEditor<Employee, number>
  implements AfterViewInit
{
  container = viewChild.required<ElementRef<HTMLDivElement>>('container');

  /** Local signal for UI state during editing */
  ratingValue = signal(3);
  readonly stars = [1, 2, 3, 4, 5];
  readonly Math = Math;

  constructor() {
    super();
    // Sync from base class currentValue (handles control vs value)
    effect(() => {
      this.ratingValue.set(this.currentValue() ?? 3);
    });
  }

  ngAfterViewInit(): void {
    setTimeout(() => this.container().nativeElement.focus(), 0);
  }

  onStarClick(star: number): void {
    this.ratingValue.set(star);
    this.commitValue(star);
  }

  onKeyDown(event: KeyboardEvent): void {
    const current = this.ratingValue();
    if (event.key === 'ArrowLeft' && current > 1) {
      this.ratingValue.set(Math.max(1, current - 0.5));
    } else if (event.key === 'ArrowRight' && current < 5) {
      this.ratingValue.set(Math.min(5, current + 0.5));
    } else if (event.key === 'Enter') {
      this.commitValue(this.ratingValue());
    } else if (event.key === 'Escape') {
      this.cancelEdit();
    }
  }
}

// demos/react/src/demos/employee-management/components/editors/StarRatingEditor.tsx
import { useEffect, useRef, useState } from 'react';

/**
 * StarRatingEditor - Interactive 5-star rating editor with keyboard support
 * Matches Angular: app-star-rating-editor
 */
interface StarRatingEditorProps {
  value: number;
  onCommit: (value: number) => void;
  onCancel: () => void;
}

export function StarRatingEditor({ value, onCommit, onCancel }: StarRatingEditorProps) {
  const [currentValue, setCurrentValue] = useState(value ?? 3);
  const containerRef = useRef<HTMLDivElement>(null);
  const stars = [1, 2, 3, 4, 5];

  useEffect(() => {
    // Focus the container after mount
    setTimeout(() => containerRef.current?.focus(), 0);
  }, []);

  const handleStarClick = (star: number) => {
    setCurrentValue(star);
    onCommit(star);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'ArrowLeft' && currentValue > 1) {
      setCurrentValue((v) => Math.max(1, v - 0.5));
    } else if (e.key === 'ArrowRight' && currentValue < 5) {
      setCurrentValue((v) => Math.min(5, v + 0.5));
    } else if (e.key === 'Enter') {
      onCommit(currentValue);
    } else if (e.key === 'Escape') {
      onCancel();
    }
  };

  return (
    <div ref={containerRef} className="star-rating-editor" tabIndex={0} onKeyDown={handleKeyDown}>
      {stars.map((star) => (
        <span
          key={star}
          className={`star-rating-editor__star ${
            star <= currentValue ? 'star-rating-editor__star--filled' : 'star-rating-editor__star--empty'
          }`}
          onClick={() => handleStarClick(star)}
        >
          {star <= Math.round(currentValue) ? '★' : '☆'}
        </span>
      ))}
      <span className="star-rating-editor__label">{currentValue.toFixed(1)}</span>
    </div>
  );
}
