// demos/react/src/shell/DemoIndex.tsx
import { Link } from 'react-router-dom';

/**
 * Demo index page — rendered at `/` listing every registered route.
 */

export interface DemoIndexEntry {
  path: string;
  label: string;
  description?: string;
}

export function DemoIndex({ entries }: { entries: readonly DemoIndexEntry[] }) {
  return (
    <main className="demo-index">
      <header className="demo-index-header">
        <h1>Toolbox Web — React Demos</h1>
        <p>Pick a demo below or navigate directly via URL.</p>
      </header>
      <ul className="demo-index-list">
        {entries.map((entry) => (
          <li key={entry.path} className="demo-index-card">
            <Link to={`/${entry.path}`} className="demo-index-link">
              <h2 className="demo-index-title">{entry.label}</h2>
              {entry.description && <p className="demo-index-description">{entry.description}</p>}
              <span className="demo-index-route">/{entry.path}</span>
            </Link>
          </li>
        ))}
      </ul>
    </main>
  );
}

// demos/vue/src/shell/DemoIndex.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';

defineProps<{
  entries: ReadonlyArray<{ path: string; label: string; description?: string }>;
}>();
</script>

<template>
  <main class="demo-index">
    <header class="demo-index-header">
      <h1>Toolbox Web — Vue Demos</h1>
      <p>Pick a demo below or navigate directly via URL.</p>
    </header>
    <ul class="demo-index-list">
      <li v-for="entry in entries" :key="entry.path" class="demo-index-card">
        <RouterLink :to="`/${entry.path}`" class="demo-index-link">
          <h2 class="demo-index-title">{{ entry.label }}</h2>
          <p v-if="entry.description" class="demo-index-description">{{ entry.description }}</p>
          <span class="demo-index-route">/{{ entry.path }}</span>
        </RouterLink>
      </li>
    </ul>
  </main>
</template>
