// demos/angular/src/demo-index.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DEMOS } from './demos.registry';

@Component({
  selector: 'demo-index',
  standalone: true,
  imports: [RouterLink],
  styles: [
    `
      :host {
        display: block;
      }
    `,
  ],
  template: `
    <main class="demo-index">
      <header class="demo-index-header">
        <h1>Toolbox Web — Angular Demos</h1>
        <p>Pick a demo below or navigate directly via URL.</p>
      </header>
      <ul class="demo-index-list">
        @for (entry of demos; track entry.path) {
          <li class="demo-index-card">
            <a [routerLink]="['/', entry.path]" class="demo-index-link">
              <h2 class="demo-index-title">{{ entry.label }}</h2>
              @if (entry.description) {
                <p class="demo-index-description">{{ entry.description }}</p>
              }
              <span class="demo-index-route">/{{ entry.path }}</span>
            </a>
          </li>
        }
      </ul>
    </main>
  `,
})
export class DemoIndexComponent {
  readonly demos = DEMOS;
}

// demos/vue/src/shell/DemoIndex.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';

defineProps<{
  entries: ReadonlyArray<{ path: string; label: string; description?: string }>;
}>();
</script>

<template>
  <main class="demo-index">
    <header class="demo-index-header">
      <h1>Toolbox Web — Vue Demos</h1>
      <p>Pick a demo below or navigate directly via URL.</p>
    </header>
    <ul class="demo-index-list">
      <li v-for="entry in entries" :key="entry.path" class="demo-index-card">
        <RouterLink :to="`/${entry.path}`" class="demo-index-link">
          <h2 class="demo-index-title">{{ entry.label }}</h2>
          <p v-if="entry.description" class="demo-index-description">{{ entry.description }}</p>
          <span class="demo-index-route">/{{ entry.path }}</span>
        </RouterLink>
      </li>
    </ul>
  </main>
</template>
