// demos/react/src/demos/employee-management/components/editors/StatusSelectEditor.tsx
import { useEffect, useRef, useState } from 'react';

/**
 * StatusSelectEditor - Dropdown status editor with icons
 * Matches Angular: app-status-select-editor
 */
interface StatusSelectEditorProps {
  value: string;
  onCommit: (value: string) => void;
  onCancel: () => void;
}

interface StatusConfig {
  bg: string;
  text: string;
  icon: string;
}

const STATUS_OPTIONS: string[] = ['Active', 'Remote', 'On Leave', 'Contract', 'Terminated'];
const STATUS_CONFIG: Record<string, StatusConfig> = {
  Active: { bg: '#d4edda', text: '#155724', icon: '✓' },
  Remote: { bg: '#cce5ff', text: '#004085', icon: '🏠' },
  'On Leave': { bg: '#fff3cd', text: '#856404', icon: '🌴' },
  Contract: { bg: '#e2e3e5', text: '#383d41', icon: '📄' },
  Terminated: { bg: '#f8d7da', text: '#721c24', icon: '✗' },
};

export function StatusSelectEditor({ value, onCommit, onCancel }: StatusSelectEditorProps) {
  const [currentValue, setCurrentValue] = useState(value || 'Active');
  const selectRef = useRef<HTMLSelectElement>(null);

  useEffect(() => {
    // Focus the select after mount
    setTimeout(() => selectRef.current?.focus(), 0);
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newValue = e.target.value;
    setCurrentValue(newValue);
    onCommit(newValue);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      onCancel();
    }
  };

  return (
    <div className="status-select-editor">
      <select
        ref={selectRef}
        className="status-select-editor__select"
        value={currentValue}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
      >
        {STATUS_OPTIONS.map((status) => (
          <option key={status} value={status}>
            {STATUS_CONFIG[status].icon} {status}
          </option>
        ))}
      </select>
    </div>
  );
}

// demos/vue/src/demos/employee-management/components/editors/StatusSelectEditor.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';

/**
 * StatusSelectEditor - Dropdown editor for employee status
 * Matches React: StatusSelectEditor.tsx
 */
const props = defineProps<{
  value: string;
}>();

const emit = defineEmits<{
  commit: [value: string];
  cancel: [];
}>();

const selectRef = ref<HTMLSelectElement | null>(null);
const currentValue = ref(props.value || 'Active');

const statusOptions = [
  { value: 'Active', icon: '✓' },
  { value: 'Remote', icon: '🏠' },
  { value: 'On Leave', icon: '🌴' },
  { value: 'Contract', icon: '📄' },
  { value: 'Terminated', icon: '✗' },
];

watch(
  () => props.value,
  (newValue) => {
    currentValue.value = newValue || 'Active';
  },
);

onMounted(() => {
  setTimeout(() => selectRef.value?.focus(), 0);
});

const handleChange = (event: Event) => {
  const target = event.target as HTMLSelectElement;
  currentValue.value = target.value;
  emit('commit', target.value);
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape') {
    event.preventDefault();
    emit('cancel');
  }
};
</script>

<template>
  <div class="status-select-editor">
    <select
      ref="selectRef"
      :value="currentValue"
      class="status-select-editor__select"
      @change="handleChange"
      @keydown="handleKeyDown"
    >
      <option v-for="status in statusOptions" :key="status.value" :value="status.value">
        {{ status.icon }} {{ status.value }}
      </option>
    </select>
  </div>
</template>
